version: '2'
services:
  postgres:
    image: postgres:9.5
    restart: always
    environment:
       POSTGRES_PASSWORD: dot_ledger
       POSTGRES_USER: dot_ledger
       POSTGRES_DB: dot_ledger
    expose:
      - "5432"
  dotledger:
    build: .
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      DATABASE_URL: "postgres://dot_ledger:dot_ledger@postgres/dot_ledger?sslmode=disable"
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
    ports:
      - "3000:3000"